 id |            name            |                                                                                                                                                      description                                                                                                                                                      |      image       | price_cents | quantity |         created_at         |         updated_at         | category_id 
----+----------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+-------------+----------+----------------------------+----------------------------+-------------
  1 | Men's Classy shirt         | Park post-ironic trust fund narwhal umami meggings synth yuccie. Squid readymade green juice pop-up godard 8-bit keytar bespoke. 3 wolf moon shoreditch bushwick vice leggings. Try-hard hammock polaroid post-ironic irony crucifix park. Hoodie humblebrag distillery umami meh vinegar biodiesel.                  | apparel1.jpg     |        6499 |       23 | 2018-07-20 18:48:38.89151  | 2018-07-20 18:48:38.89151  |           1
  2 | Women's Zebra pants        | Pinterest butcher shabby chic wolf sustainable park mlkshk small batch. Vhs 8-bit try-hard pbr&b synth. Meh you probably haven't heard of them blog artisan wolf microdosing pickled put a bird on it. Pour-over green juice pinterest.                                                                               | apparel2.jpg     |       12499 |       18 | 2018-07-20 18:48:39.018509 | 2018-07-20 18:48:39.018509 |           1
  3 | Hipster Hat                | Twee hoodie slow-carb. Freegan fanny pack locavore typewriter xoxo etsy. Microdosing hoodie truffaut biodiesel pork belly heirloom wolf. Polaroid keffiyeh truffaut pour-over carry meditation cardigan tousled. Flexitarian 90's artisan kitsch yolo park twee. Fap flexitarian thundercats cray loko.               | apparel3.jpg     |        3449 |        4 | 2018-07-20 18:48:39.1943   | 2018-07-20 18:48:39.1943   |           1
  4 | Hipster Socks              | Skateboard kombucha cold-pressed. Kogi sartorial beard xoxo forage heirloom ugh mixtape. 3 wolf moon normcore lo-fi quinoa. Art party organic slow-carb carry fap asymmetrical street. Cornhole poutine wayfarers blog drinking.                                                                                      | apparel4.jpg     |        2500 |        8 | 2018-07-20 18:48:39.620013 | 2018-07-20 18:48:39.620013 |           1
  5 | Russian Spy Shoes          | Wolf meh five dollar toast tacos cliche. Small batch godard sartorial kale chips paleo letterpress selfies put a bird on it. Selfies gastropub stumptown. Normcore heirloom lo-fi authentic. Bespoke lomo lumbersexual thundercats chambray carry banjo yr. Hella forage selfies vinegar listicle squid polaroid ugh. | apparel5.jpg     |      122500 |        8 | 2018-07-20 18:48:39.800658 | 2018-07-20 18:48:39.800658 |           1
  6 | Human Feet Shoes           | Vhs kale chips distillery wayfarers truffaut cronut. Next level craft beer blue bottle. Tote bag dreamcatcher celiac cronut. Intelligentsia fashion axe tote bag.                                                                                                                                                     | apparel6.jpg     |       22450 |       82 | 2018-07-20 18:48:39.91599  | 2018-07-20 18:48:39.91599  |           1
  7 | Modern Skateboards         | Sriracha kale chips five dollar toast typewriter schlitz listicle lomo stumptown. Food truck gastropub helvetica keffiyeh disrupt tilde. Whatever thundercats umami small batch flexitarian tote bag intelligentsia. Salvia park hammock selvage meggings yr.                                                         | electronics1.jpg |       16449 |       40 | 2018-07-20 18:48:40.060796 | 2018-07-20 18:48:40.060796 |           2
  8 | Hotdog Slicer              | Waistcoat deep v crucifix raw denim loko keytar. Lo-fi venmo xoxo salvia synth mustache. Hoodie aesthetic lomo you probably haven't heard of them bespoke cliche swag. Aesthetic seitan meditation tattooed lomo direct trade migas xoxo. Bitters plaid tofu single-origin coffee yuccie try-hard keytar.             | electronics2.jpg |        2600 |        3 | 2018-07-20 18:48:40.225421 | 2018-07-20 18:48:40.225421 |           2
  9 | World's Largest Smartwatch | Heirloom kickstarter before they sold out williamsburg typewriter keffiyeh art party. Fap scenester cold-pressed iphone artisan. Goth before they sold out vinegar fashion axe cardigan deep v small batch. Roof leggings lo-fi master asymmetrical. Cred wes anderson health.                                        | electronics3.jpg |      202629 |       32 | 2018-07-20 18:48:40.403907 | 2018-07-20 18:48:40.403907 |           2
 10 | Optimal Sleeping Bed       | Green juice cred chambray cornhole cronut. Pbr&b chicharrones pop-up kitsch authentic. Plaid venmo chillwave before they sold out everyday heirloom freegan. Kale chips semiotics yuccie disrupt.                                                                                                                     | furniture1.jpg   |      305200 |      320 | 2018-07-20 18:48:40.55209  | 2018-07-20 18:48:40.55209  |           3
 11 | Electric Chair             | Park franzen twee scenester meggings post-ironic. Semiotics gluten-free salvia paleo occupy narwhal wes anderson. Mustache hammock ramps dreamcatcher flexitarian. Cold-pressed food truck pug iphone trust fund waistcoat post-ironic.                                                                               | furniture2.jpg   |       98765 |        2 | 2018-07-20 18:48:40.730026 | 2018-07-20 18:48:40.730026 |           3
 12 | Red Bookshelf              | Literally letterpress mustache. Irony kombucha green juice letterpress vegan flexitarian neutra cold-pressed. Drinking gluten-free brooklyn freegan loko bespoke. Vinyl stumptown literally helvetica irony distillery jean shorts. +1 gentrify gastropub street tousled polaroid hammock paleo.                      | furniture3.jpg   |      248375 |        0 | 2018-07-20 18:48:41.068924 | 2018-07-20 18:48:41.068924 |           3
(12 rows)

